default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: jars_development

test: &test
  <<: *default
  database: jars_test

production:
  <<: *default
  database: jars_production

cucumber:
  <<: *test