default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: opotto_development

test: &test
  <<: *default
  database: opotto_test

cucumber:
  <<: *test
