---
:concurrency: 5
staging:
  :concurrency: <%= ENV['MAX_THREADS'] %>
production:
  :concurrency: <%= ENV['MAX_THREADS'] %>
:queues:
  - default
  - paypal_checker
  - friend_sync
  - payments
  - mailers
