---
:concurrency: 5
staging:
  :concurrency: 5
production:
  :concurrency: 10
:queues:
  - default
  - paypal_checker
  - friend_sync
  - payments
:limits:
  paypal_checker: 5
  friend_sync: 10
  payments: 2
