#!/bin/bash
set -x
set -e

[[ ! -s \"$(git rev-parse --git-dir)/shallow\" ]] || git fetch --unshallow
git push git@heroku.com:opotto-staging.git develop:master
heroku run rake db:migrate --app opotto-staging
# heroku run rake db:seed --app opotto-staging
heroku run rake sitemap:refresh --app opotto-staging
